version: "3.2"

services:
  api:
    image: asturov/master:latest
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
    environment:
      - INCREMENTOR_URL=astworker
      - INCREMENTOR_PORT=8080
      - DB_URL=postgres
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=111
    depends_on:
      - "postgres"
      - "astworker"
    networks:
      - web-net

  astworker:
    image: asturov/worker:latest
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
    depends_on:
      - "postgres"
    environment:
      - DB_URL=postgres
      - DB_PORT=5432
      - DB_NAME=testdb
      - DB_USER=postgres
      - DB_PASSWORD=111
    networks:
      - web-net

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - web-net
    environment:
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  web-net:
  
volumes:
  db-data:
