version: "3.2"

services:
  api:
    image: asturov/master
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
    environment:
      - INCREMENTOR_URL:incrementor
      - INCREMENTOR_PORT:8085
      - DB_URL:postgres
      - DB_PORT:5432
      - DB_NAME:testdb
      - DB_USER:fibonacci
      - DB_PASSWORD:111
    depends_on:
      - "postgres"
      - "incrementor"
    networks:
      - web-net

  incrementor:
    image: asturov/master
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
    depends_on:
      - "postgres"
    environment:
      - DB_URL:postgres
      - DB_PORT:5432
      - DB_NAME:testdb
      - DB_USER:postgres
      - DB_PASSWORD:111
    networks:
      - web-net

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD:111
      - POSTGRES_DB:testdb
      - POSTGRES_USER:postgres
    networks:
      - web-net
networks:
  web-net:

volumes:
  db-data: